"""initial

Revision ID: 2f751890ebd9
Revises: 8d3f237e9ccc
Create Date: 2026-07-13 07:30:05.958205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f751890ebd9'
down_revision: Union[str, Sequence[str], None] = '8d3f237e9ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sets', 'calories',
               existing_type=sa.DOUBLE_PRECISION(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sets', 'calories',
               existing_type=sa.DOUBLE_PRECISION(),
               nullable=False)
    # ### end Alembic commands ###
