"""pr by type(3)

Revision ID: 3b61c7a763d3
Revises: e7f2ebf4af3a
Create Date: 2026-07-14 07:09:34.686945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b61c7a763d3'
down_revision: Union[str, Sequence[str], None] = 'e7f2ebf4af3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
