"""pr updated type to bool

Revision ID: 45721cd02730
Revises: 3b61c7a763d3
Create Date: 2026-07-14 07:15:57.119075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45721cd02730'
down_revision: Union[str, Sequence[str], None] = '3b61c7a763d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sets', 'is_pr_updated',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sets', 'is_pr_updated',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
