"""pr structure

Revision ID: 50f06e9f5327
Revises: 87c3ee745e57
Create Date: 2026-07-14 06:41:42.186541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f06e9f5327'
down_revision: Union[str, Sequence[str], None] = '87c3ee745e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_records', sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.add_column('personal_records', sa.Column('workout_set_id', sa.Integer(), nullable=False))
    op.create_index('ix_personal_record_user_exercise_date', 'personal_records', ['user_id', 'exercise_id', 'achieved_at'], unique=False)
    op.create_foreign_key(None, 'personal_records', 'workout_sessions', ['workout_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_records', type_='foreignkey')
    op.drop_index('ix_personal_record_user_exercise_date', table_name='personal_records')
    op.drop_column('personal_records', 'workout_set_id')
    op.drop_column('personal_records', 'id')
    # ### end Alembic commands ###
