"""initial

Revision ID: 588d393a5a59
Revises: 258b7040e89a
Create Date: 2026-08-06 11:59:56.144829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588d393a5a59'
down_revision: Union[str, Sequence[str], None] = '258b7040e89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_sets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_duration', sa.Integer(), nullable=True),
    sa.Column('target_distance', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_failure', sa.Boolean(), nullable=False),
    sa.Column('is_drop_set', sa.Boolean(), nullable=False),
    sa.Column('is_super_set', sa.Boolean(), nullable=False),
    sa.Column('routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_sets_routine_exercise_id'), 'routine_sets', ['routine_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_sets_routine_exercise_id'), table_name='routine_sets')
    op.drop_table('routine_sets')
    # ### end Alembic commands ###
