"""session name

Revision ID: 621cb848ab70
Revises: 163930ca4734
Create Date: 2026-07-17 06:30:51.830901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621cb848ab70'
down_revision: Union[str, Sequence[str], None] = '163930ca4734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'name')
    # ### end Alembic commands ###
