"""hash2hashed

Revision ID: 6ae45ec2d94a
Revises: 7c4601da4359
Create Date: 2026-07-11 06:03:55.329143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '6ae45ec2d94a'
down_revision: Union[str, Sequence[str], None] = '7c4601da4359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtools$execution_history')
    op.add_column('refresh_tokens', sa.Column('token_hashed', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hashed'), 'refresh_tokens', ['token_hashed'], unique=True)
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token_hashed'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'token_hashed')
    op.create_table('dbtools$execution_history',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('hash', sa.CLOB(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('statement', sa.CLOB(), nullable=True),
    sa.Column('times', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dbtools$execution_history_pk')),
    oracle_tablespace='DATA'
    )
    # ### end Alembic commands ###
