"""add index to set

Revision ID: 87c3ee745e57
Revises: 889d758581c1
Create Date: 2026-07-14 06:12:46.816812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c3ee745e57'
down_revision: Union[str, Sequence[str], None] = '889d758581c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workout_sets_order', 'workout_sets', ['workout_exercise_id', 'set_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_sets_order', table_name='workout_sets')
    # ### end Alembic commands ###
