"""add index to session

Revision ID: 889d758581c1
Revises: f56973506e26
Create Date: 2026-07-14 05:59:56.457519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889d758581c1'
down_revision: Union[str, Sequence[str], None] = 'f56973506e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_exercises_routine_id'), table_name='routine_exercises')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.create_index('ix_workout_session_user_started_at', 'workout_sessions', ['user_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_session_user_started_at', table_name='workout_sessions')
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_routine_exercises_routine_id'), 'routine_exercises', ['routine_id'], unique=False)
    # ### end Alembic commands ###
