"""initial

Revision ID: 8d3f237e9ccc
Revises: 7c6e641ee58c
Create Date: 2026-07-13 07:27:53.411201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3f237e9ccc'
down_revision: Union[str, Sequence[str], None] = '7c6e641ee58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('category', sa.Integer(), nullable=False))
    op.add_column('exercises', sa.Column('equipment', sa.Integer(), nullable=False))
    op.add_column('exercises', sa.Column('body_part', sa.Integer(), nullable=False))
    op.add_column('exercises', sa.Column('sub_body_part', sa.Integer(), nullable=True))
    op.drop_column('exercises', 'sub_body_part_code')
    op.drop_column('exercises', 'body_part_code')
    op.drop_column('exercises', 'equipment_code')
    op.drop_column('exercises', 'category_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('category_code', sa.INTEGER(), nullable=False))
    op.add_column('exercises', sa.Column('equipment_code', sa.INTEGER(), nullable=False))
    op.add_column('exercises', sa.Column('body_part_code', sa.INTEGER(), nullable=False))
    op.add_column('exercises', sa.Column('sub_body_part_code', sa.INTEGER(), nullable=True))
    op.drop_column('exercises', 'sub_body_part')
    op.drop_column('exercises', 'body_part')
    op.drop_column('exercises', 'equipment')
    op.drop_column('exercises', 'category')
    # ### end Alembic commands ###
