"""Initial schema

Revision ID: 9d31ffc55895
Revises: 
Create Date: 2026-07-05 11:00:34.997245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '9d31ffc55895'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtools$execution_history')
    op.create_foreign_key(None, 'personal_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_records', type_='foreignkey')
    op.create_table('dbtools$execution_history',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('hash', sa.CLOB(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('statement', sa.CLOB(), nullable=True),
    sa.Column('times', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dbtools$execution_history_pk')),
    oracle_tablespace='DATA'
    )
    # ### end Alembic commands ###
