"""pr by type(2)

Revision ID: b2a5507327db
Revises: fa487a37d1a1
Create Date: 2026-07-14 06:58:52.460681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a5507327db'
down_revision: Union[str, Sequence[str], None] = 'fa487a37d1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'personal_records', 'workout_sets', ['workout_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_records', type_='foreignkey')
    # ### end Alembic commands ###
