"""seperate exercises

Revision ID: c87cab318523
Revises: 588d393a5a59
Create Date: 2026-08-08 05:54:49.071537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87cab318523'
down_revision: Union[str, Sequence[str], None] = '588d393a5a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('default_weight_untrained', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('default_weight_novice', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('default_weight_intermediate', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('default_weight_advanced', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('default_weight_elite', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('training_level', sa.String(length=20), server_default='untrained', nullable=True))

    op.execute("""
        UPDATE exercises
        SET
            default_weight_untrained = 0,
            default_weight_novice = 0,
            default_weight_intermediate = 0,
            default_weight_advanced = 0,
            default_weight_elite = 0
    """)


    for column_name in (
        "default_weight_untrained",
        "default_weight_novice",
        "default_weight_intermediate",
        "default_weight_advanced",
        "default_weight_elite",
    ):
        op.alter_column(
            "exercises",
            column_name,
            existing_type=sa.Float(),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'training_level')
    op.drop_column('exercises', 'default_weight_elite')
    op.drop_column('exercises', 'default_weight_advanced')
    op.drop_column('exercises', 'default_weight_intermediate')
    op.drop_column('exercises', 'default_weight_novice')
    op.drop_column('exercises', 'default_weight_untrained')
    # ### end Alembic commands ###
