"""routine icons

Revision ID: c947089cf239
Revises: c87cab318523
Create Date: 2026-08-12 05:10:01.464281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c947089cf239'
down_revision: Union[str, Sequence[str], None] = 'c87cab318523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('icon', sa.String(length=30), server_default='dumbbell', nullable=False))
    op.alter_column('users', 'training_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'untrained'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'training_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'untrained'"))
    op.drop_column('routines', 'icon')
    # ### end Alembic commands ###
