"""add prupdated

Revision ID: e7f2ebf4af3a
Revises: b2a5507327db
Create Date: 2026-07-14 07:04:15.171693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f2ebf4af3a'
down_revision: Union[str, Sequence[str], None] = 'b2a5507327db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_personal_records_workout_set_id'), 'personal_records', ['workout_set_id'], unique=False)
    op.add_column('workout_sets', sa.Column('is_pr_updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'is_pr_updated')
    op.drop_index(op.f('ix_personal_records_workout_set_id'), table_name='personal_records')
    # ### end Alembic commands ###
