"""add index order

Revision ID: f56973506e26
Revises: 2f751890ebd9
Create Date: 2026-07-14 05:33:48.775076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56973506e26'
down_revision: Union[str, Sequence[str], None] = '2f751890ebd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_routine_exercise_order', 'routine_exercises', ['routine_id', 'exercise_order'], unique=False)
    op.create_index(op.f('ix_routine_exercises_exercise_id'), 'routine_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_routine_exercises_routine_id'), 'routine_exercises', ['routine_id'], unique=False)
    op.create_index('ix_workout_exercise_order', 'workout_exercises', ['workout_session_id', 'exercise_order'], unique=False)
    op.create_index(op.f('ix_workout_exercises_workout_session_id'), 'workout_exercises', ['workout_session_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_routine_id'), 'workout_sessions', ['routine_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_routine_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_exercises_workout_session_id'), table_name='workout_exercises')
    op.drop_index('ix_workout_exercise_order', table_name='workout_exercises')
    op.drop_index(op.f('ix_routine_exercises_routine_id'), table_name='routine_exercises')
    op.drop_index(op.f('ix_routine_exercises_exercise_id'), table_name='routine_exercises')
    op.drop_index('ix_routine_exercise_order', table_name='routine_exercises')
    # ### end Alembic commands ###
