"""pr by type

Revision ID: fa487a37d1a1
Revises: 50f06e9f5327
Create Date: 2026-07-14 06:53:46.736479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa487a37d1a1'
down_revision: Union[str, Sequence[str], None] = '50f06e9f5327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_records', sa.Column('record_type', sa.Integer(), nullable=False))
    op.add_column('personal_records', sa.Column('value', sa.Float(), nullable=False))
    op.drop_column('personal_records', 'estimated_1rm')
    op.drop_column('personal_records', 'max_weight')
    op.drop_column('personal_records', 'max_volume')
    op.drop_column('personal_records', 'max_reps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_records', sa.Column('max_reps', sa.INTEGER(), nullable=True))
    op.add_column('personal_records', sa.Column('max_volume', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('personal_records', sa.Column('max_weight', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('personal_records', sa.Column('estimated_1rm', sa.DOUBLE_PRECISION(), nullable=True))
    op.drop_column('personal_records', 'value')
    op.drop_column('personal_records', 'record_type')
    # ### end Alembic commands ###
